DROP TABLE IF EXISTS beer.countries CASCADE;
DROP TABLE IF EXISTS beer.servingtemp CASCADE;
DROP TABLE IF EXISTS beer.locationtypes CASCADE;
DROP TABLE IF EXISTS beer.srm CASCADE;
DROP TABLE IF EXISTS beer.categories CASCADE;
DROP TABLE IF EXISTS beer.styles CASCADE;
DROP TABLE IF EXISTS beer.beers CASCADE;
DROP TABLE IF EXISTS beer.breweries CASCADE;